### ISSUE TITLE
华北电力大学（保定）第十七届视像头四轮源代码

### ISSUE THREAD

**Issue by HammerTa** [ittuann/Awesome-IntelligentCarRace#2]
### Clear and concise description of your idea

你好，这是我代码仓库的github链接，由于最近事务繁杂，还请劳烦各位将我的仓库添加到项目中，不胜感激

### Describe how the idea would be helpful

https://github.com/HammerTa/intelegent_car_race_program_17

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Remember to follow the community guidelines and be friendly.

**Comment by wu58430** [comment]
国一🤩

**Comment by HammerTa** [comment]
萝老师别这样，你又不是不知道我去年只拿了省一 @wu58430

**Comment by wu58430** [comment]
> 萝老师别这样，你又不是不知道我去年只拿了省一 @wu58430

第二年用了这个代码，改了改，你不就国一，还国特了🥳

**Comment by ittuann** [comment]
已经更新进去啦~
