### ISSUE TITLE
17届多车编队组-东北林业大学-国一

### ISSUE THREAD

**Issue by wu58430** [ittuann/Awesome-IntelligentCarRace#3]
### Clear and concise description of your idea

项目地址：https://github.com/wu58430/RUBO-UDIPM

### Describe how the idea would be helpful

用于图像透视变换以及去畸变的小软件
可以很方便的使用鼠标完成图像的透视变换操作
并附带C代码，配合逐飞/龙邱库可轻松移植到单片机上
采用指针映射图像地址方式，在高分辨率图片上比打表法更省RAM，更快
但在较低分辨率上，该方法RAM占用更高,推荐RAM在128KB以上，96KB即可

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Remember to follow the community guidelines and be friendly.

**Comment by ittuann** [comment]
已经更新进去啦~
