### ISSUE TITLE
中国石油大学（华东）智能视觉组开源

### ISSUE THREAD

**Issue by shuoshuof** [ittuann/Awesome-IntelligentCarRace#7]
### 开源链接

https://blog.csdn.net/qtzbxjg/article/details/128621625?spm=1001.2014.3001.5501

### 组别

智能视觉组

### 项目名称、学校

中国石油大学（华东）

### 获奖、年份

国一，2022

### 备注信息

因为开源分成了三个仓库，这里直接给出CSDN的汇总信息，博客中会给出每个部分的仓库地址。

**Comment by ittuann** [comment]
感谢补充信息！网页已经完成更新~
