### ISSUE TITLE
[Submit] 

### ISSUE THREAD

**Issue by xingchenpid** [ittuann/Awesome-IntelligentCarRace#8]
### 开源链接

[国之重器.zip](https://github.com/ittuann/Awesome-IntelligentCarRace/files/12737581/default.zip)

### 组别

负压电磁

### 项目名称、学校

合肥学院攀高

### 获奖、年份

2023省一

### 备注信息

http://t.csdn.cn/vhg9y

**Comment by ittuann** [comment]
感谢提供信息~ 

但是我似乎没有查找到十八届-负压电磁组-合肥学院-攀高队的信息？可以麻烦补充一下信息来源嘛

**Comment by ittuann** [comment]
新的信息被提供在 issue (#9)。所以这个 issue 将会被关闭。
