### ISSUE TITLE
[Submit] 

### ISSUE THREAD

**Issue by xingchenpid** [ittuann/Awesome-IntelligentCarRace#9]
### 开源链接

[国之重器.zip](https://github.com/ittuann/Awesome-IntelligentCarRace/files/12745546/default.zip)

### 组别

负压电磁

### 项目名称、学校

昌平队合肥学院

### 获奖、年份

2023省一

### 备注信息

http://t.csdn.cn/kERvy

**Comment by ittuann** [comment]
感谢补充信息！网页已经完成更新~

**Comment by panyyc** [comment]
thank you very much
